### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by kariston607** [roy6307/Goose-Goose-Goose#1]
What are the detailed steps to use this？

**Comment by roy6307** [comment]
open sln file with Visual Studio 2019.
And just compile and inject it.

**Comment by kariston607** [comment]
> 使用Visual Studio 2019打开sln文件。只需编译并注入它。

Compilation failed, alerting me to missing pch.h

**Comment by JustPruss** [comment]
> > 使用Visual Studio 2019打开sln文件。只需编译并注入它。
> 
> Compilation failed, alerting me to missing pch.h


To fix this open the menu Project -> Goose Goose Goose Property -> C/C++ -> Precompiled Headers and just turn it off
