### ISSUE TITLE
Eunable(problem appear)

### ISSUE THREAD

**Issue by zj52024** [roy6307/Goose-Goose-Goose#11]
Hello Roy6307, it is me again. The problem this time is that cheating cannot be used. The general situation is that after the eunable is opened, the game directly collapses. Do you encounter such a problem? No matter where you open this feature, it will collapse. Is it updated?

**Comment by zj52024** [comment]
I continue to pay attention to your project almost every day, because he is so cool. I am also trying to solve the problem you encountered. There is no clue for the time being

**Comment by zj52024** [comment]
Even! Player list window can not read the character name in the game

**Comment by zj52024** [comment]
Is it normal for you?

**Comment by zj52024** [comment]
The game should be updated, you need to update the new offset

**Comment by roy6307** [comment]
Recently, I was thinking about what to do about the ESP function. So I forgot to update Offset.hpp first. I'm sorry. But I think I found a solution. I'm thinking of reflecting the solution as soon as possible. And if there is a function that you want to add, please leave it on Pull Request. It'll be a big help.

**Comment by zj52024** [comment]
> Recently, I was thinking about what to do about the ESP function. So I forgot to update Offset.hpp first. I'm sorry. But I think I found a solution. I'm thinking of reflecting the solution as soon as possible. And if there is a function that you want to add, please leave it on Pull Request. It'll be a big help.

Okay, just like I am optimizing this project now. After you update the offset, I can try it. I study almost every day
