### ISSUE TITLE
vs

### ISSUE THREAD

**Issue by xiaoxiaoverynice** [roy6307/Goose-Goose-Goose#15]
What is the compiler of vs

**Comment by xiaoxiaoverynice** [comment]
c1047

**Comment by roy6307** [comment]
I'm so sorry for late response!

First of all, **I DO NOT RECOMMEND YOU TO USE THIS PROJECT.
STILL UNSTABLE. AND I CAN'T SURE THAT THE ANTI-CHEAT IS WORKING.**

I think there is a problem with Minhook.
Please recompile [Minhook](https://github.com/TsudaKageyu/minhook) and replace "libMinHook.x64.lib" with your own.
If you still have a problem even you changed the file, please reopen an issue.
Thank you!
