### ISSUE TITLE
Ask for help 

### ISSUE THREAD

**Issue by JustPruss** [roy6307/Goose-Goose-Goose#2]
Hi
I tried to compile your project and got the following error.
![image](https://user-images.githubusercontent.com/42804023/170626856-da1ead6b-0dcf-46f0-b9d7-99ea140003a4.png)

**Comment by Prinxino** [comment]
Hi
I have the same issue, did you find out how to fix it?

**Comment by amfisevan** [comment]
Hi. I finished building the dll file and injected to the goose goose duck. I can see the UI ingame but the problem is that the game crashes and doesn't really work. can you solve this problem?
