### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by Prinxino** [roy6307/Goose-Goose-Goose#5]
Hi,
After i inject there is a small issue, the game doesnt respond to my keyboard or mouse.
I cant move or do anything.
Any ideas why?

**Comment by roy6307** [comment]
Without any picture or detailed description, I can't tell you a solution.
But I think there are two cases.

1. When the cheat menu is opened, only the cheat menu will receive all keyboard inputs. To close the menu, please press 'INSERT key'.

2. If the game still ignore 'keyboard inputs' even the cheat menu is closed, press ALT+TAB twice or click somewhere else and return to game.

Sorry for my poor english and late response.
I hope these helps you.
